spring.application.name=bookify-dev
spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start_and_stop
server.port=8082
spring.jpa.hibernate.ddl-auto=none

spring.flyway.locations=db/migration,data
bookify.maximum.books.borrowed=2
bookify.overdue.days=3