#
# Test
#

#
# Test
#

spring.application.name=bookify-prod
spring.datasource.url=jdbc:postgresql://127.0.0.1:50253/bookify
spring.datasource.username=bookify
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver
spring.docker.compose.enabled=false
