-- Create EVENT_PUBLICATION table for Spring's event publication mechanism
CREATE TABLE EVENT_PUBLICATION (
    ID VARCHAR(255) PRIMARY KEY,
    EVENT_TYPE VARCHAR(255) NOT NULL,
    LISTENER_ID VARCHAR(255) NOT NULL,
    PUBLICATION_DATE TIMESTAMP NOT NULL,
    SERIALIZED_EVENT TEXT NOT NULL
);